### PR TITLE
Codegen jl

### PR DESCRIPTION
**Pull request by amellnik**
Squashing a few layers to reduce resulting container somewhat.

### CODE REVIEW

**Comment by amellnik** [comment]
Edit: probably not worth merging -- I just saw all the changes to LLVM.jl which will change a bunch of stuff upstream of this.

**Comment by tshort** [comment]
I'm curious, what was the size impact of this?

**Comment by amellnik** [comment]
I didn't check the image size, but it was maybe 15% of the layers.  I probably could have reduced it a lot more by reordering stuff a bit -- this was just the quick-and-dirty version.  I was trying to reduce the size to see if it helped deploy it to heroku -- currently it crashes while starting after a minute or so without producing any logs.  There's probably something else going on.

I saw that the new LLVM can be used without a source build of Julia.  Does codegen still need a source build?  If not that could greatly reduce the size of the image.

**Comment by tshort** [comment]
If LLVM works without a source build, I think Codegen should, too. That'll be nice. `libjulia` might be tricky.

**Comment by tshort** [comment]
FYI, the latest CodeGen.jl works with the latest LLVM.jl, and that combination works on 32-bit Julia in Linux. I haven't tried in Docker, but it should simplify things. It's nice for running locally, too.

**Comment by tshort** [comment]
Just to clarify: that combination works with the 32-bit binary nightly of Julia.

**Pull request closed without merging**
